#!/usr/bin/env python3

import json
import subprocess
import sys

from shared import *

sys.tracebacklimit = 0
uuid = None

config_schema = {
    "source": {
        "url": "",
        "branch": ""
    }
}

def main(config):
    eprint(config)
    validate_schema(config, config_schema)
    url = config["source"]["url"]
    branch = config["source"]["branch"]
    user = None
    password = None
    token = None

    if "user" in config["source"]:
        user = config["source"]["user"]

    if "password" in config["source"]:
        password = config["source"]["password"]

    if user is not None and password is not None:
        login_data = login(url, user, password)
        token = login_data['authToken']

    return getTimeline(url, branch, token)


config = json.loads(sys.stdin.read())

uuid = main(config)
eprint(uuid)

if uuid is not None:
    #print(json.dumps([{ "ref": "%s" % uuid[0:10] }]))
    print(json.dumps({"version":{"ref": "%s" % uuid[0:10] },"metadata":[]}))
else:
    print(json.dumps({"version":{"ref": "none" },"metadata":[]}))
exit(0)