#!/usr/bin/env python3

import json
import subprocess
import sys

from shared import *

sys.tracebacklimit = 0
uuid = None

config_schema = {
    "source": {
        "url": "",
        "branch": ""
    }
}

def main(config):
    eprint(config)
    validate_schema(config, config_schema)
    url = config["source"]["url"]
    branch = config["source"]["branch"]
    user = None
    password = None
    token = None

    if "user" in config["source"]:
        user = config["source"]["user"]

    if "password" in config["source"]:
        password = config["source"]["password"]

    if user is not None and password is not None:
        pload = {"payload":{"name":user, "password":password}}
        token = login(url, pload)
    else:
        token = loginAnonym(url)

    return getTimeline(url, branch, token)


config = json.loads(sys.stdin.read())

uuid = main(config)
eprint(uuid)

if uuid is not None:
    #print(json.dumps([{ "ref": "%s" % uuid[0:10] }]))
    #print(json.dumps({"version":{"ref": "%s" % uuid[0:10] },"metadata":[]}))
    #print(json.dumps([{"version":{"ref": "%s" % uuid[0:10] }}]))
    print(json.dumps({"version":{"ref": "%s" % uuid[0:10] }}))
    #print(json.dumps(["ref:%s" % uuid[0:10]]))
else:
    # empty version to keep Concourse happy
    print('[]')
exit(0)