#!/usr/bin/env python3

import json
import sys

from shared import *

sys.tracebacklimit = 0

config_schema = {
    "source": {
        "url": "",
        "branch": ""
    },
    "version": {
        "ref": ""
    }
}

def main(path, config):
    cookies = None

    validate_schema(config, config_schema)
    
    url = config["source"]["url"]
    branch = config["source"]["branch"]
    user = None
    password = None
    ref = config["version"]["ref"]

    if "user" in config["source"]:
        user = config["source"]["user"]

    if "password" in config["source"]:
        password = config["source"]["password"]

    # login erforderlich
    if user is not None and password is not None:
        pload = {"payload":{"name":user, "password":password}}
        login(url, pload)
    else:
        loginAnonym(url)

    cookies = getCookieToken()

    tarFilePath = getTarball(path, url, ref, cookies)

    os.system("tar -xf " + tarFilePath + " -C " + path)
    #os.system("rm " + tarFilePath)

    return ref


path = sys.argv[1]
config = json.loads(sys.stdin.read())

uuid = main(path, config)

print(json.dumps({"version":{"ref": "%s" % uuid[0:10] },"metadata":[]}))
exit(0)