#!/usr/bin/env python3

import json
import sys

from shared import *

sys.tracebacklimit = 0

config_schema = {
    "source": {
        "url": "",
        "branch": ""
    },
    "version": {
        "ref": ""
    }
}

def main(path, config):
    validate_schema(config, config_schema)
    
    url = config["source"]["url"]
    branch = config["source"]["branch"]
    user = None
    password = None
    token = None
    ref = config["version"]["ref"]

    if "user" in config["source"]:
        user = config["source"]["user"]

    if "password" in config["source"]:
        password = config["source"]["password"]

    # login erforderlich
    if user is not None and password is not None:
        pload = {"payload":{"name":user, "password":password}}
        token = login(url, pload)
        if token is None:
            return None
    else:
        token = loginAnonym(url)

    # get tarball with cookie data
    tarFilePath = getTarball(path, url, ref, getCookieToken())
    if tarFilePath is None:
        return None

    # unpack and delete tar source
    os.system("tar -xf " + tarFilePath + " -C " + path)
    os.system("rm " + tarFilePath)

    # write timelineItem as File
    timelineItem = getTimeline(url, branch, token)
    eprint(timelineItem)
    with open("timelineItem.json", "w") as timeline_data_file:
        json.dump(timelineItem, timeline_data_file, indent=4, sort_keys=True)

    return timelineItem


path = sys.argv[1]
config = json.loads(sys.stdin.read())
eprint(config)

timelineItem = main(path, config)
if timelineItem is None:
    # delete token and next try to login
    delAuthTokens()
    timelineItem = main(path, config)

if timelineItem is not None:
    print(json.dumps({"version":{"ref": "%s" % timelineItem['uuid'][0:10] },"metadata":[timelineItem]}))
else:
    # empty version to keep Concourse happy
    print('[]')
exit(0)